---
title: "ML Research Validation"
subtitle: 'Replication & extension of "_Fraud Detection using Machine Learning (Oza, 2018)_"'
author: "Salman Faris"
date: "20 July 2024"
format:
  pdf: default
  html:
    page-layout: full
    self-contained: true
    grid:
      margin-width: 350px
execute:
  echo: fenced
reference-location: margin
citation-location: margin
---

# Introduction

_Fraud Detection using Machine Learning (Oza, 2018)_ proposed a class weight strategy to tackle the problem of imbalanced classes in payments fraud detection. The author showed that choosing a suitable class weight in a classifier can be sufficient to flag fraud detections with a reasonably low false positive rate whilst maintaining high accuracy.

# Method

We replicate the results of (Oza, 2018) using the same data and the same preprocessing steps, some of which were not specified in their paper but rather in their code (which has been a common occurrence in our experience replicating machine learning papers).

# Experimental evaluation

We run our experiments on a MacBook Pro M1 Pro with 8 CPU cores and 4 GPU cores. Unfortunately, (Oza, 2018) did not specify the machine they used to train their models.

Some holes in the paper:

- Did not specify hyperparameters where used for each model.
- Did not specify standard scaling step for SVM + RBF. Found only in code.

::: {#tbl-panel layout-ncol=2}
| Algorithm | Recall | Precision | F1 | AUPRC |
| --------------------- | ------ | --------- | ------ | ----- |
| Logistic Regression | 0.9935 | 0.8243 | 0.9010 | 0.9606 |
| Linear SVM | 0.9935 | 0.7421 | 0.8500 | 0.9496 |
| SVM with RBF kernel | 0.9870 | 0.7172 | 0.8307 | 0.9717|
| Decision Tree (_new_) | 0.9935 | 0.6308 | 0.7717 | 0.9896|

: Replication results (ours) {#tbl-first}

| Algorithm             | Recall | Precision | F1     | AUPRC  |
| --------------------- | ------ | --------- | ------ | ------ |
| Logistic Regression   | 0.9983 | 0.4416    | 0.6123 | 0.9248 |
| Linear SVM            | 0.9983 | 0.4432    | 0.6139 | 0.9161 |
| SVM with RBF kernel   | 0.9934 | 0.5871    | 0.7381 | 0.9855 |
| Decision Tree (_new_) | N/A    | N/A       | N/A    | N/A    |

: Original results {#tbl-second}

<span style="color:blue">**TRANSFER**</span> dataset evaluation on validation set
:::

::: {#tbl-panel layout-ncol=2}
| Algorithm | Recall | Precision | F1 | AUPRC |
| --------------------- | ------ | --------- | ------ | ----- |
| Logistic Regression | 0.9870 | 0.1565 | 0.2702 | 0.7620|
| Linear SVM | 0.9011 | 0.1440 | 0.2483 |0.7027|
| SVM with RBF kernel | 0.9011 | 0.1483 | 0.2546 |0.7674|
| Decision Tree (_new_) | 0.6742 | 0.1906 | 0.2971 |0.5838|

: Replication results (ours) {#tbl-first}

| Algorithm             | Recall | Precision | F1     | AUPRC  |
| --------------------- | ------ | --------- | ------ | ------ |
| Logistic Regression   | 0.9822 | 0.1561    | 0.2692 | 0.7235 |
| Linear SVM            | 0.9352 | 0.1263    | 0.2226 | 0.6727 |
| SVM with RBF kernel   | 0.9773 | 0.1315    | 0.2318 | 0.7598 |
| Decision Tree (_new_) | N/A    | N/A       | N/A    | N/A    |

: Original results {#tbl-second}

<span style="color:red">**CASH OUT**</span> dataset evaluation on validation set
:::

::: {#tbl-panel layout-ncol=2}
| Algorithm | Ideal class weight |
| --------------------- | :----------------: |
| Logistic Regression | 14 |
| Linear SVM | 12 |
| SVM with RBF kernel | 13 |
| Decision Tree (_new_) | 305 |

: Replication results (ours) {#tbl-first}

| Algorithm             | Ideal class weight |
| --------------------- | :----------------: |
| Logistic Regression   |         70         |
| Linear SVM            |         39         |
| SVM with RBF kernel   |         16         |
| Decision Tree (_new_) |        N/A         |

: Original results {#tbl-second}

<span style="color:blue">**TRANSFER**</span> dataset ideal class weights
:::

::: {#tbl-panel layout-ncol=2}
| Algorithm | Ideal class weight |
| --------------------- | :----------------: |
| Logistic Regression | 124 |
| Linear SVM | 112 |
| SVM with RBF kernel | 81 |
| Decision Tree (_new_) | 30 |

: Replication results (ours) {#tbl-first}

| Algorithm             | Ideal class weight |
| --------------------- | :----------------: |
| Logistic Regression   |        145         |
| Linear SVM            |        132         |
| SVM with RBF kernel   |        128         |
| Decision Tree (_new_) |        N/A         |

: Original results {#tbl-second}

<span style="color:red">**CASH OUT**</span> dataset ideal class weights
:::

# Conclusion
